# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Github-Repository-Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Github-Repository-Swift
pod 'SDWebImage', '~> 4.0'
end
